### ISSUE TITLE
Download link of the pre-trained weights is  wrong. It is BIPNet pre-trained model link.

### ISSUE THREAD

**Issue by bluedream1121** [akshaydudhane16/Burstormer#2]
Hello. Thank you for releasing your impressive CVPR 2023 work, Burstormer!

I have one question about the download links of pre-trained model.

When I go into the trained model page of Burst Super-Resolution, the pre-trained weights is BIPNet, not Burstormer. 

I think it is a mistake of the link. 

Can you update the link of pre-trained weights to the one of Burstormer?

Thank you.

**Comment by akshaydudhane16** [comment]
Thank you for noticing this. I will update the links in 2 days.

**Comment by YoungP2001** [comment]
Hello, the pre-trained weight is still wrong. Can you update the link of pre-trained weights to the Burstormer?
